database:
  ConnectionStrings:
    default: "Server=127.0.0.1; Database=openmod; Port=3306; User=root; Password=password" # See https://www.connectionstrings.com/mysql/ for more information on making ConnectionStrings
Shops:
  CanBuyItems: true
  CanSellItems: true
  CanBuyVehicles: true
  CanSellVehicles: true #not yet implemented
